In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({'Stock Tickers':['AAPL','XOM','IBM','NFLX','AAPL',
                               'META','XOM','PFE','MSFT','AMZN','MCD',
                               'AAPL','GOOGL','JNJ','AAPL','XOM',
                               'NVDA','GOOGL','IBM','PG','NVDA','ABT'
                               'JPM','AAPL','AMZN','HD','MA','V',
                               'LLY','AAPL','AMZN','GOOGL','META',
                               'BAC','XOM','AMZN','AAPL','TMO','LLY',
                               'MSFT','BRK.B','UNH','AAPL','JNR','V',
                               'MA','PEP','KO','AAPL','IBM','XOM','V',
                               'AMZN','TSLA']})
df

   Stock Tickers
0           AAPL
1            XOM
2            IBM
3           NFLX
4           AAPL
5           META
6            XOM
7            PFE
8           MSFT
9           AMZN
10           MCD
11          AAPL
12         GOOGL
13           JNJ
14          AAPL
15           XOM
16          NVDA
17         GOOGL
18           IBM
19            PG
20          NVDA
21        ABTJPM
22          AAPL
23          AMZN
24            HD
25            MA
26             V
27           LLY
28          AAPL
29          AMZN
30         GOOGL
31          META
32           BAC
33           XOM
34          AMZN
35          AAPL
36           TMO
37           LLY
38          MSFT
39         BRK.B
40           UNH
41          AAPL
42           JNR
43             V
44            MA
45           PEP
46            KO
47          AAPL
48           IBM
49           XOM
50             V
51          AMZN
52          TSLA

In [4]:
df['Stock Tickers'].value_counts()

AAPL      9
AMZN      5
XOM       5
V         3
GOOGL     3
IBM       3
MSFT      2
META      2
NVDA      2
MA        2
LLY       2
PEP       1
JNR       1
BAC       1
UNH       1
BRK.B     1
KO        1
TMO       1
ABTJPM    1
HD        1
PG        1
JNJ       1
MCD       1
PFE       1
NFLX      1
TSLA      1
Name: Stock Tickers, dtype: int64

# **References and Additional Learning**

## **Websites**

- **[pandas.DataFrame.value_counts](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html) from pandas.pydata.org**

# **Connect**
- **Feel free to connect with Adrian on [YouTube](https://www.youtube.com/channel/UCPuDxI3xb_ryUUMfkm0jsRA), [LinkedIn](https://www.linkedin.com/in/adrian-dolinay-frm-96a289106/), [Twitter](https://twitter.com/DolinayG), [GitHub](https://github.com/ad17171717) and [Odysee](https://odysee.com/@adriandolinay:0). Happy coding!**